Django - level 4/learningTemplates/basicApp/urls.py
from django.urls import path
from basicApp import views

#Templates tagging
app_name = 'basicApp'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other')
]

Django - level 4/learningTemplates/learningTemplates/urls.py
from django.contrib import admin
from django.urls import path,include
from basicApp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicApp/',include('basicApp.urls'))
]

Django - level 4/learningTemplates/basicApp/models.py
from django.db import models

# Create your models here.

Django - level 4/learningTemplates/basicApp/views.py
from django.shortcuts import render

def index(request):
    context_dict = {'text':'Hello world','number':100}
    return render(request,'basicApp/index.html',context_dict)

def other(request):
    return render(request,'basicApp/other.html')

def relative(request):
    return render(request,'basicApp/relative_url_templates.html')

Django - level 4/learningTemplates/templates/basicApp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basicApp:other' %}">Other</a>
      </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {# Anything outside of this will be inherited if you use extend.#}
        {% endblock %}
    </div>

  </body>
</html>

Django - level 4/learningTemplates/templates/basicApp/index.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
{% load my_extras %}
{% block  body_block %}
    <h1>Welcome to index!</h1>
    <h1>{{text|cutout:'Hello'}}</h1>
    <h1>{{number|add:'99'}}</h1>
{% endblock %}}
    

Django - level 4/learningTemplates/templates/basicApp/other.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
{% block body_block %}
    <h1>Welcome to other!</h1>
    <h1>Example of inheritance</h1>
{% endblock  %}
    

Django - level 4/learningTemplates/templates/basicApp/relative_url_templates.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css">
    <script src="main.js"></script>
</head>
<body>
        <h1>Welcome to Relatve_url_templates!</h1>
        <a href="{% url 'basicApp:other' %}">Click for other</a>
        <a href="{% url 'admin:index' %}">Admin</a>
        <a href="{% url 'index' %}">Index</a>


</body>
</html>